### ISSUE TITLE
[Bug]: Error on startup, ArgumentException: Type 'Keyboard' has not been registered as a control layout

### ISSUE THREAD

**Issue by coolbond1** [Rune580/LethalCompanyInputUtils#49] opened 2024-06-07 04:52 UTC
### Acknowledgements

- [x] I use r2modman/thunderstore and will provide a modpack code or zip
- [X] I understand that InputUtils only officially supports the latest version of Lethal Company

### Lobby Related

No

### Lobby Acknowledgements

- [X] I understand that all players must have the exact same mod list and have made sure that all players have the exact same modlist.

### InputUtils Version

0.7.4

### Game Version

v50

### Describe the bug

Error on startup. Cant access the steam interface ingame and if its somehow brought up cant close it forcing a restart of the game.

### Reproduction steps

Open game.

### ModPack code or file

018ff09a-3bef-bd36-ae4e-cb24967493d2

### Logs

[LogOutput.log](https://github.com/user-attachments/files/15710007/LogOutput.log)
[Message:   BepInEx] BepInEx 5.4.21.0 - Lethal Company (5/19/2024 8:57:55 PM)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [FixPluginTypesSerialization 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.2.1.0]
[Info   :   BepInEx] 3 patcher plugins loaded
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Message:FixPluginTypesSerialization] Using the config cache
[Info   :FixPluginTypesSerialization] Running under Unity v2022.3.9
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 30 plugins to load
[Info   :   BepInEx] Loading [MoreCompany 1.9.1]
[Info   :MoreCompany] Loading MoreCompany...
[Info   :MoreCompany] Loading SETTINGS...
[Info   :MoreCompany] Checking: C:\Users\Artur\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Lethal Fuckery\BepInEx\plugins/MoreCompanyCosmetics
[Info   :MoreCompany] Loading COSMETICS...
[Info   :MoreCompany] Loading DEFAULT COSMETICS...
[Info   :MoreCompany] Loaded cosmetic: builtin.3dglasses from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.bunnyears from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.denimhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.fancyglasses from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.partyglasses from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.gunholster from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.hardhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.jesterhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.kittyears from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.mimemask from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.fancypants from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.outoforder from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.partyhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.plaguemask from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.propellerhat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.eyeballs from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.rudolph from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.santahat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.slimething from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.tophat from bundle
[Info   :MoreCompany] Loaded cosmetic: builtin.watch from bundle
[Info   :MoreCompany] Loading USER COSMETICS...
[Info   :MoreCompany] Loaded MoreCompany FULLY
[Info   :   BepInEx] Loading [ModelReplacementAPI 2.4.5]
[Info   :meow.ModelReplacementAPI] Plugin meow.ModelReplacementAPI is loaded!
[Info   :   BepInEx] Loading [Oneshot_Collection 0.1.0]
[Info   :   Console] Oneshot_Collection.OneshotCollection
[Info   :meow.ModelReplacementAPI] Registering body replacement type ModelReplacement.MRALULA to suit name alula.
[Info   :meow.ModelReplacementAPI] Registering body replacement type ModelReplacement.MRNIKO2 to suit name niko.
[Info   :meow.ModelReplacementAPI] Registering body replacement type ModelReplacement.MRNIKOGAS to suit name gasmaskniko.
[Info   :meow.ModelReplacementAPI] Registering body replacement type ModelReplacement.MRCALAMUS to suit name calamus.
[Info   :Oneshot_Collection] Plugin .com.Ghost.Oneshot is loaded!
[Info   :   BepInEx] Loading [LCMaxSoundsFix 1.2.0]
[Info   :LCMaxSoundsFix] Plugin LCMaxSoundsFix is loaded!
[Debug  :LCMaxSoundsFix] Binding audio config...
[Debug  :LCMaxSoundsFix] Applying audio settings...
[Info   :LCMaxSoundsFix] Audio settings (numRealVoices=128; numVirtualVoices=1024) are applied.
[Info   :   BepInEx] Loading [Starlancer AI Fix 3.6.0]
[Info   :Starlancer AI Fix] Starlancer AI Fix Online.
[Info   :   BepInEx] Loading [Accurate Stamina Display 2.1.1]
[Info   :Accurate Stamina Display] Accurate Stamina Display v2.1.1 loaded
[Info   :   BepInEx] Loading [Classic Suit Restoration 2.0.2]
[Info   :Classic Suit Restoration] Classic Suit Restoration v2.0.2 loaded
[Info   :   BepInEx] Loading [Lethal Company Input Utils 0.7.4]
[Info   :Lethal Company Input Utils] Registered InputUtilsExtendedMouse Layout Override!
[Info   :Lethal Company Input Utils] InputUtils 0.7.4 has finished loading!
[Error  : Unity Log] ArgumentException: Type 'Keyboard' has not been registered as a control layout
Parameter name: type
Stack trace:
UnityEngine.InputSystem.InputManager.TryLoadControlLayout (System.Type type) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:0)
UnityEngine.InputSystem.InputSystem.LoadLayout[TControl] () (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:0)
LethalCompanyInputUtils.Utils.LayoutExporter..cctor () (at /home/runner/work/LethalCompanyInputUtils/LethalCompanyInputUtils/LethalCompanyInputUtils/Utils/LayoutExporter.cs:12)
Rethrow as TypeInitializationException: The type initializer for 'LethalCompanyInputUtils.Utils.LayoutExporter' threw an exception.
LethalCompanyInputUtils.LethalCompanyInputUtilsPlugin.Awake () (at /home/runner/work/LethalCompanyInputUtils/LethalCompanyInputUtils/LethalCompanyInputUtils/LethalCompanyInputUtilsPlugin.cs:50)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

[Info   :   BepInEx] Loading [CSync 5.0.1]
[Info   :     CSync] CSync successfully applied patches.
[Info   :   BepInEx] Loading [Poltergeist 1.1.0]
[Debug  :     CSync] Successfully registered config instance InstanceKey { Guid = coderCleric.Poltergeist, AssemblyQualifiedName = Poltergeist.PoltergeistConfig, Poltergeist, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null }.
[Info   :Poltergeist] Found expected structure for monitor transpiler!
[Info   :Poltergeist] Plugin coderCleric.Poltergeist v1.1.0 is loaded!
[Info   :   BepInEx] Loading [Coroner 1.6.2]
[Info   :   Coroner] Injecting patch into Landmine.SpawnExplosion...
[Info   :   Coroner] Done.
[Info   :   Coroner] Plugin Coroner (com.elitemastereric.coroner) is loaded!
[Info   :   Coroner] Coroner loading language support: en
[Info   :   Coroner] Loading language data from config folder: C:\Users\Artur\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Lethal Fuckery\BepInEx\config/EliteMasterEric-Coroner
[Info   :   Coroner] Coroner loading language support: en
[Info   :   Coroner] Loading language data from config folder: C:\Users\Artur\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Lethal Fuckery\BepInEx\config/EliteMasterEric-Coroner
[Info   :   Coroner] Checking for LC_API...
[Info   :   Coroner] LCAPI is not present.
[Info   :   Coroner] LC_API is not present! Skipping registration...
[Info   :   BepInEx] Loading [LethalLib 0.16.0]
[Info   : LethalLib] LethalLib loaded!!
[Info   :   BepInEx] Loading [Interactive Terminal API 1.0.0]
[Info   :Interactive Terminal API] Game managers have been patched
[Info   :Interactive Terminal API] Interactive Terminal API 1.0.0 has been loaded successfully.
[Info   :   BepInEx] Loading [More Ship Upgrades 3.7.1]
[Debug  :     CSync] Successfully registered config instance InstanceKey { Guid = com.malco.lethalcompany.moreshipupgrades, AssemblyQualifiedName = MoreShipUpgrades.Misc.LategameConfiguration, MoreShipUpgrades, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null }.
[Info   :More Ship Upgrades] Registed sample for the enemy "centipede"...
[Info   :More Ship Upgrades] Registed sample for the enemy "bunker spider"...
[Info   :More Ship Upgrades] Registed sample for the enemy "hoarding bug"...
[Info   :More Ship Upgrades] Registed sample for the enemy "flowerman"...
[Info   :More Ship Upgrades] Registed sample for the enemy "mouthdog"...
[Info   :More Ship Upgrades] Registed sample for the enemy "baboon hawk"...
[Info   :More Ship Upgrades] Registed sample for the enemy "crawler"...
[Info   :More Ship Upgrades] Registed sample for the enemy "forestgiant"...
[Info   :More Ship Upgrades] Registed sample for the enemy "manticoil"...
[Info   :More Ship Upgrades] Registed sample for the enemy "tulip snake"...
[Info   :More Ship Upgrades] Items have been setup
[Info   :More Ship Upgrades] Commands have been setup
[Info   :More Ship Upgrades] Upgrades have been setup
[Info   :More Ship Upgrades] Enemies have been patched
[Info   :More Ship Upgrades] HUD has been patched
[Info   :More Ship Upgrades] Interactables have been patched
[Info   :More Ship Upgrades] Items have been patched
[Info   :More Ship Upgrades] Game managers have been patched
[Info   :More Ship Upgrades] Weathers have been patched
[Info   :More Ship Upgrades] More Ship Upgrades 3.7.1 has been loaded successfully.
[Info   :   BepInEx] Loading [Custom Sounds 2.3.2]
[Info   :CustomSounds] "HideManagerGameObject" is correctly set to true.
[Info   :CustomSounds] Plugin CustomSounds is loaded!
[Info   :   BepInEx] Loading [LethalFixes 1.0.0]
[Info   :   BepInEx] Loading [ReservedItemSlotCore 2.0.30]
[Info   :ReservedItemSlotCore-2.0.30] BindingConfigs
[Info   :ReservedItemSlotCore-2.0.30] ReservedItemSlotCore loaded
[Info   :   BepInEx] Loading [ReservedFlashlightSlot 2.0.5]
[Info   :ReservedFlashlightSlot-2.0.5] BindingConfigs
[Info   :ReservedItemSlotCore-2.0.30] Created ReservedItemSlotData for: flashlight. Slot priority: 200
[Info   :ReservedFlashlightSlot-2.0.5] ReservedFlashlightSlot loaded
[Info   :   BepInEx] Loading [ReservedWalkieSlot 2.0.5]
[Info   :ReservedWalkieSlot-2.0.5] BindingConfigs
[Info   :ReservedItemSlotCore-2.0.30] Created ReservedItemSlotData for: walkie_talkie. Slot priority: 150
[Info   :ReservedWalkieSlot-2.0.5] ReservedWalkieSlot loaded
[Info   :   BepInEx] Loading [MaxWasUnavailable.LethalModDataLib 1.2.2]
[Debug  :MaxWasUnavailable.LethalModDataLib] Patching...
[Debug  :MaxWasUnavailable.LethalModDataLib] Patched!
[Info   :MaxWasUnavailable.LethalModDataLib] Plugin MaxWasUnavailable.LethalModDataLib is loaded!
[Info   :   BepInEx] Loading [LethalLevelLoader 1.2.0.4]
[Info   :LethalLevelLoader] LethalLevelLoader loaded!!
[Info   :LethalLevelLoader] Finding LethalBundles!
[Info   :LethalLevelLoader] Config Level Set As: User
[Info   :   BepInEx] Loading [LethalToolbox 1.0.0]
[Info   :LethalToolbox] LethalToolbox loaded!!
[Info   :   BepInEx] Loading [LC Sound Tool 1.5.1]
[Info   :LCSoundTool] Plugin LCSoundTool is loaded!
[Info   :   BepInEx] Loading [DamageMetrics 1.0.0]
[Info   :Matsuura.TestAccount666.DamageMetrics] DamageMetrics Awake
[Info   :   BepInEx] Loading [Buyable Shotgun Shells 1.1.0]
[Info   :Buyable Shotgun Shells] Shotgun Shell added to Shop for 20 credits
[Info   :Buyable Shotgun Shells] Plugin Buyable Shotgun Shells is loaded with version 1.1.0!
[Info   :   BepInEx] Loading [ReservedKeySlot 2.0.0]
[Info   :ReservedItemSlotCore-2.0.30] Created ReservedItemSlotData for: key. Slot priority: -40
[Warning:ReservedItemSlotCore-2.0.30] Attempted to create a new ReservedItemSlotData (lockpicker) with the same priority as: key. Adjusting priority to: -41
[Info   :ReservedItemSlotCore-2.0.30] Created ReservedItemSlotData for: lockpicker. Slot priority: -41
[Info   :ReservedKeySlot] ReservedKeySlot loaded
[Info   :   BepInEx] Loading [Yippee tbh mod 1.2.4]
[Info   :sunnobunno.YippeeMod] sunnobunno.YippeeMod is loading.
[Info   :sunnobunno.YippeeMod] sunnobunno.YippeeMod is loaded. Yippee!!!
[Info   :   BepInEx] Loading [CoilHeadStare 1.0.9]
[Info   :TDP.CoilHeadStare] CoilHeadStare 1.0.9 loaded.
[Info   :   BepInEx] Loading [Goku Bracken 1.5.7]
[Info   :Goku Bracken] Initializing config...
[Info   :Goku Bracken] Loading asset bundle...
[Info   :Goku Bracken] Hey it's me! Goku!
[Info   :Goku Bracken] Your files look pretty strong! I'm gonna patch them!
[Info   :   BepInEx] Loading [More Suits 1.4.3]
[Info   :More Suits] Plugin More Suits is loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   :ReservedFlashlightSlot-2.0.5] Initializing hotkeys.
[Info   :ReservedWalkieSlot-2.0.5] Initializing hotkeys.
[Warning:LCSoundTool] Networking disabled. Mod in fully client side mode, but no networked actions can take place! You can safely ignore this if you want the mod to run fully client side.
[Debug  :   BepInEx] [UnityInput] Unknown key name: OEM1, skipping remapping
[Debug  :   BepInEx] [UnityInput] Unknown key name: OEM2, skipping remapping
[Debug  :   BepInEx] [UnityInput] Unknown key name: OEM3, skipping remapping
[Debug  :   BepInEx] [UnityInput] Unknown key name: OEM4, skipping remapping
[Debug  :   BepInEx] [UnityInput] Unknown key name: OEM5, skipping remapping
[Debug  :   BepInEx] [UnityInput] Unknown key name: IMESelected, skipping remapping
[Debug  :   BepInEx] [UnityInput] Using NewInputSystem
[Info   :LethalLevelLoader] Found ExtendedMod: Asteroid13ExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: DesolationExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: CosmocosExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: GloomExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: FissionExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: AtlanticaExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: InfernisExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: EternExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: JunicExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: GratarExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: OldredExtendedMod
[Info   :LethalLevelLoader] No ExtendedMod Found In Bundle: oneshotmoons.lethalbundle. Forcefully Loading ExtendedContent!
[Info   :LethalLevelLoader] Found ExtendedMod: PorcerinExtendedMod
[Info   :LethalLevelLoader] Found ExtendedMod: PolarusExtendedMod
[Info   :LethalLevelLoader] Adding ScenePath: BarrensScene
[Info   :LethalLevelLoader] Adding ScenePath: GlenScene
[Info   :LethalLevelLoader] Adding ScenePath: RefugeScene
[Info   :LethalLevelLoader] Adding ScenePath: Asteroid13Scene
[Info   :LethalLevelLoader] Adding ScenePath: AtlanticaScene
[Info   :LethalLevelLoader] Adding ScenePath: CosmocosScene
[Info   :LethalLevelLoader] Adding ScenePath: DesolationScene
[Info   :LethalLevelLoader] Adding ScenePath: EternScene
[Info   :LethalLevelLoader] Adding ScenePath: FissionCScene
[Info   :LethalLevelLoader] Adding ScenePath: GloomScene
[Info   :LethalLevelLoader] Adding ScenePath: GratarScene
[Info   :LethalLevelLoader] Adding ScenePath: InfernisScene
[Info   :LethalLevelLoader] Adding ScenePath: JunicScene
[Info   :LethalLevelLoader] Adding ScenePath: OldredScene
[Info   :LethalLevelLoader] Adding ScenePath: PolarusScene
[Info   :LethalLevelLoader] Adding ScenePath: AcidirScene
[Info   : Unity Log] Saving changed settings

**Comment by Rune580** [comment] 2024-06-07 16:11
duplicate of #46

**Closed by Rune580** 2024-06-07 16:11 UTC
Labels: bug
