### ISSUE TITLE
Controller/keyboard binds not changing if they default to ""

### ISSUE THREAD

**Issue by KlutzyBubbles** [Rune580/LethalCompanyInputUtils#22] opened 2024-01-27 13:42 UTC
Read and fill in the following:

- [x] I use r2modman

- [x] I acknowledge that issues from manual installs may not get resolved as they are difficult for mod developers to debug.

- [x] I acknowledge that InputUtils only officially supports the latest version of Lethal Company.

- [x] I acknowledge that this issue may be closed if all players in the lobby don't have the exact same mod list and versions.

- [x] I have filled or marked all fields marked with `<!-- Required -->` including this checkbox and acknowledge that failure to do so may result in my issue being closed immediately and deleted in 24 hours if I fail to fill or mark the required fields. Failure to mark this checkbox **Doesn't** mean you can ignore the requirements.

---

**Versions**
InputUtils Version:  ex: 0.6.0
Lethal Company Version: ex: v49

**Describe the bug**
In game controller/keyboard binding getting cleared on custom keybinds (in game keybinds stay changed) that default to nothing in my mod BetterEmotes.

**To Reproduce**
1. Install BetterEmotes
2. Launch game (default settings)
3. Go to settings (either in game or in main menu) -> Change Keybinds
4. Change a controller/keyboard input that doesn't already have a default
5. Confirm changes and go back to the main menu
6. Go back into Change Keybinds and the input is blank again

**Expected behavior**
Keybind stays changed

**Logs**
There are simply no logs when any of the steps are done, unless im missing an option somewhere, my bepinex is set to all logs

**ModPack Code or File**
018d4b24-3701-a35e-3617-c40f3f7c7925

**Additional context**
Not sure if its an issue with the way i have it implemented but for extra information, this is how i have implemented it https://github.com/KlutzyBubbles/lc-better-emotes/blob/lcvr-compat/BetterEmote/Utils/Keybinds.cs

**Comment by Rune580** [comment] 2024-01-27 13:55
This was something I fixed with the attribute style api, but I forgot to do the same for the runtime/builder api.

**Comment by Rune580** [comment] 2024-01-27 13:56
Could you try again with the artifact from the PR and let me know if the issue is still present. https://github.com/Rune580/LethalCompanyInputUtils/actions/runs/7679068148

**Closed** 2024-01-27 14:07 UTC
